// Code generated by sqlc. DO NOT EDIT.

package postgres

import (
	"database/sql"
)

type Author struct {
	ID   int64
	Name string
	Bio  sql.NullString
}

type Todo struct {
	ID    int64
	Title string
}
